// All 47 Kenya counties with sub-counties and comprehensive towns/localities

export const KENYA_COUNTIES = [
  {
    name: "Nairobi",
    center: { lat: -1.2921, lng: 36.8219 },
    zoom: 11,
    subCounties: [
      { name: "Westlands", towns: ["Westlands", "Parklands", "Kilimani", "Kileleshwa", "Lavington", "Spring Valley", "Riverside", "Hurlingham", "Upper Hill", "Milimani", "Raphta Road", "Woodlands"] },
      { name: "Dagoretti North", towns: ["Riruta", "Kawangware", "Gitaru", "Dagoretti Corner", "Ruthimitu", "Waithaka", "Satellite"] },
      { name: "Dagoretti South", towns: ["Uthiru", "Mutuini", "Kinoo", "Ondiri", "Regen", "Mountain View"] },
      { name: "Langata", towns: ["Karen", "Langata", "South C", "South B", "Nyayo Highrise", "Otiende", "Mugumoini", "Hardy", "Bomas"] },
      { name: "Kibra", towns: ["Kibera", "Woodley", "Olympic", "Lindi", "Laini Saba", "Silanga", "Soweto East", "Kambi Muru"] },
      { name: "Roysambu", towns: ["Roysambu", "TRM Area", "Kahawa West", "Garden Estate", "Ridgeways", "Githurai 44", "Githurai 45", "Lucky Summer"] },
      { name: "Kasarani", towns: ["Kasarani", "Mwiki", "Sunton", "Clay City", "Njiru", "Mwihoko", "Ruai", "Kariobangi", "Safari Park"] },
      { name: "Ruaraka", towns: ["Ruaraka", "Kariobangi South", "Baba Dogo", "Utalii", "Mathare North", "Babadogo"] },
      { name: "Embakasi South", towns: ["Imara Daima", "Kwa Njenga", "Kwa Reuben", "Pipeline", "Kware", "Nyayo Estate"] },
      { name: "Embakasi North", towns: ["Embakasi", "Utawala", "Mihang'o", "Kamulu", "Joska", "Mowlem"] },
      { name: "Embakasi Central", towns: ["Kayole", "Komarock", "Matopeni", "Greenfield"] },
      { name: "Embakasi East", towns: ["Umoja 1", "Umoja 2", "Mowlem", "Kariobangi North", "Tena Estate"] },
      { name: "Embakasi West", towns: ["Fedha", "Heartlands", "Savanna", "Shooting Range", "Mihango", "Greenspan"] },
      { name: "Makadara", towns: ["Makadara", "Maringo", "Viwandani", "Harambee", "Hamza", "Jericho", "Jerusalem", "Jogoo Road"] },
      { name: "Kamukunji", towns: ["Eastleigh North", "Eastleigh South", "Airbase", "California", "Pumwani", "Shauri Moyo"] },
      { name: "Starehe", towns: ["Nairobi CBD", "Ngara", "Pangani", "Ziwani", "Kariokor", "Landimawe", "Nairobi West", "Bahati"] },
      { name: "Mathare", towns: ["Mathare", "Mabatini", "Hospital", "Huruma", "Mlango Kubwa", "Kiamaiko", "Gitathuru"] },
    ],
  },
  {
    name: "Mombasa",
    center: { lat: -4.0435, lng: 39.6682 },
    zoom: 12,
    subCounties: [
      { name: "Changamwe", towns: ["Changamwe", "Chaani", "Port Reitz", "Kipevu", "Airport", "Miritini", "Mikindani"] },
      { name: "Jomvu", towns: ["Jomvu Kuu", "Mikindani", "Magongo", "Mishomoroni"] },
      { name: "Kisauni", towns: ["Kisauni", "Bamburi", "Shanzu", "Mwakirunge", "Mtopanga", "Bombolulu", "Kongowea", "Mlaleo"] },
      { name: "Likoni", towns: ["Likoni", "Mtongwe", "Shelly Beach", "Timbwani", "Bofu", "Mwachinga"] },
      { name: "Mvita", towns: ["Mombasa CBD", "Old Town", "Tudor", "Majengo", "Ganjoni", "Mkadini", "English Point"] },
      { name: "Nyali", towns: ["Nyali", "Frere Town", "Ziwa la Ng'ombe", "Mkomani", "Kadzandani", "Mwembe Tayari", "Links Road"] },
    ],
  },
  {
    name: "Kwale",
    center: { lat: -4.1817, lng: 39.4520 },
    zoom: 9,
    subCounties: [
      { name: "Msambweni", towns: ["Msambweni", "Diani Beach", "Ukunda", "Galu", "Tiwi", "Shimba Hills", "Kinondo", "Chale"] },
      { name: "Lungalunga", towns: ["Lungalunga", "Vanga", "Shimoni", "Wasini", "Majoreni", "Mkwiro"] },
      { name: "Matuga", towns: ["Kwale Town", "Mwereni", "Tiwi", "Kombani", "Mazeras", "Tsunza", "Ngombeni"] },
      { name: "Kinango", towns: ["Kinango", "Mackinnon Road", "Samburu", "Mwavumbo", "Ndavaya", "Mukurumudzi", "Puma"] },
    ],
  },
  {
    name: "Kilifi",
    center: { lat: -3.5107, lng: 39.9093 },
    zoom: 9,
    subCounties: [
      { name: "Kilifi North", towns: ["Kilifi Town", "Mtwapa", "Vipingo", "Takaungu", "Mavueni", "Kikambala", "Shimo la Tewa"] },
      { name: "Kilifi South", towns: ["Mariakani", "Rabai", "Mnarani", "Bofa", "Chamari", "Ruruma", "Kadzinuni"] },
      { name: "Kaloleni", towns: ["Kaloleni", "Mwele", "Kayafungo", "Mariakani (Kaloleni)", "Bamba"] },
      { name: "Rabai", towns: ["Rabai", "Ruruma", "Mwatate (Kilifi)", "Kisurutini", "Kikoneni"] },
      { name: "Ganze", towns: ["Ganze", "Bamba", "Jaribuni", "Vitengeni", "Garashi"] },
      { name: "Malindi", towns: ["Malindi", "Watamu", "Gede", "Mambrui", "Sabaki", "Kakuyuni", "Mida Creek"] },
      { name: "Magarini", towns: ["Magarini", "Ngomeni", "Garashi", "Adu", "Marafa", "Ribe", "Gongoni"] },
    ],
  },
  {
    name: "Tana River",
    center: { lat: -1.5373, lng: 39.9093 },
    zoom: 8,
    subCounties: [
      { name: "Garsen", towns: ["Garsen", "Witu", "Kipini", "Hindi (Tana)", "Tana Delta", "Hewani"] },
      { name: "Galole", towns: ["Hola", "Ngao", "Mnazini", "Sailoni", "Mikinduni"] },
      { name: "Bura", towns: ["Bura", "Bangale", "Madogo", "Wayu", "Chewani"] },
    ],
  },
  {
    name: "Lamu",
    center: { lat: -2.2686, lng: 40.9020 },
    zoom: 9,
    subCounties: [
      { name: "Lamu East", towns: ["Faza", "Kiunga", "Pate", "Siyu", "Ndau", "Tchundwa"] },
      { name: "Lamu West", towns: ["Lamu Town", "Mpeketoni", "Mokowe", "Witu", "Hindi", "Kiwayu", "Shela", "Matondoni"] },
    ],
  },
  {
    name: "Taita-Taveta",
    center: { lat: -3.4071, lng: 38.4975 },
    zoom: 9,
    subCounties: [
      { name: "Taveta", towns: ["Taveta", "Mahoo", "Chala", "Bomani", "Njukini", "Challa"] },
      { name: "Wundanyi", towns: ["Wundanyi", "Werugha", "Mwanda", "Mbololo", "Mwakitau", "Ilole", "Ngerenyi"] },
      { name: "Mwatate", towns: ["Mwatate", "Bura (Taita)", "Kishamba", "Chawia", "Iyale", "Mwanda"] },
      { name: "Voi", towns: ["Voi", "Manyani", "Sagalla", "Kasigau", "Ikanga", "Tsavo"] },
    ],
  },
  {
    name: "Garissa",
    center: { lat: -0.4532, lng: 39.6461 },
    zoom: 8,
    subCounties: [
      { name: "Garissa Township", towns: ["Garissa Town", "Township", "Galbet", "Iftin", "Waberi"] },
      { name: "Balambala", towns: ["Balambala", "Dujis", "Dertu", "Nanighi"] },
      { name: "Lagdera", towns: ["Modogashe", "Benane", "Goreale", "Hadado"] },
      { name: "Dadaab", towns: ["Dadaab", "Liboi", "Lagodera", "Hagadera"] },
      { name: "Fafi", towns: ["Bura East", "Nanighi", "Jarajila", "Sangailu"] },
      { name: "Ijara", towns: ["Ijara", "Masalani", "Sangailu", "Hulugho"] },
    ],
  },
  {
    name: "Wajir",
    center: { lat: 1.7471, lng: 40.0573 },
    zoom: 8,
    subCounties: [
      { name: "Wajir North", towns: ["Bute", "Gurar", "Wargadud", "Lakole"] },
      { name: "Wajir East", towns: ["Habaswein", "Kutulo", "Lagbogol", "Griftu"] },
      { name: "Tarbaj", towns: ["Tarbaj", "Griftu", "Wargadud", "Korondille"] },
      { name: "Wajir West", towns: ["Wajir Town", "Griftu", "Barwaqo"] },
      { name: "Eldas", towns: ["Eldas", "Diif", "Arbajahan", "Biyamadow"] },
      { name: "Wajir South", towns: ["Benane", "Diff", "Khorof Harar"] },
    ],
  },
  {
    name: "Mandera",
    center: { lat: 3.9366, lng: 41.8670 },
    zoom: 8,
    subCounties: [
      { name: "Mandera East", towns: ["Mandera Town", "Khalalio", "Neboi", "Arabia"] },
      { name: "Banissa", towns: ["Banissa", "Dandu", "Malkamari", "Guticha"] },
      { name: "Mandera North", towns: ["Rhamu", "Elele", "Ashabito", "Sala"] },
      { name: "Mandera South", towns: ["Lafey", "Bulla Mpya", "Takaba South"] },
      { name: "Mandera West", towns: ["Takaba", "Shimbir Fatuma", "Kiliwehiri"] },
      { name: "Lafey", towns: ["Lafey", "Libehia", "Fino"] },
    ],
  },
  {
    name: "Marsabit",
    center: { lat: 2.3284, lng: 37.9899 },
    zoom: 8,
    subCounties: [
      { name: "Moyale", towns: ["Moyale Town", "Sololo", "Butiye", "Golbo", "Turbi"] },
      { name: "North Horr", towns: ["North Horr", "Maikona", "Dukana", "Kalacha", "Bubisa"] },
      { name: "Saku", towns: ["Marsabit Town", "Kargi", "Logologo", "Sagante", "Badasa"] },
      { name: "Laisamis", towns: ["Laisamis", "Loiyangalani", "South Horr", "Korr", "Merille", "Illeret"] },
    ],
  },
  {
    name: "Isiolo",
    center: { lat: 0.3524, lng: 38.0003 },
    zoom: 9,
    subCounties: [
      { name: "Isiolo North", towns: ["Isiolo Town", "Bula Pesa", "Wabera", "Boras", "Ngare Mara", "Chari"] },
      { name: "Isiolo South", towns: ["Merti", "Garbatulla", "Kinna", "Oldonyiro", "Cherab", "Garba Tulla"] },
    ],
  },
  {
    name: "Meru",
    center: { lat: 0.0467, lng: 37.6490 },
    zoom: 9,
    subCounties: [
      { name: "Igembe South", towns: ["Maua", "Igembe", "Mutuati", "Athwana", "Njia", "Kaaga"] },
      { name: "Igembe Central", towns: ["Kangeta", "Antubochiu", "Akachiu", "Amwamba", "Nkando"] },
      { name: "Igembe North", towns: ["Mikinduri", "Laare", "Ruiri", "Uuru", "Kamweline"] },
      { name: "Tigania West", towns: ["Kianjai", "Mbeu", "Amwamba", "Githongo", "Kibirichia (Meru)"] },
      { name: "Tigania East", towns: ["Miathene", "Mitunguu", "Karama", "Muthara", "Lare"] },
      { name: "North Imenti", towns: ["Meru Town", "Ntima", "Kibirichia", "Nkubu", "Mutuara"] },
      { name: "Buuri", towns: ["Timau", "Buuri", "Githongo", "Ruiri", "Kisima (Meru)", "Kariene"] },
      { name: "Central Imenti", towns: ["Nkubu", "Kariene", "Kiagu", "Mitoro", "Kiirua"] },
      { name: "South Imenti", towns: ["Igoji", "Mwimbi", "Nchiru", "Kigari", "Muringene", "Kibung'a"] },
    ],
  },
  {
    name: "Tharaka-Nithi",
    center: { lat: -0.3000, lng: 37.9000 },
    zoom: 9,
    subCounties: [
      { name: "Maara", towns: ["Chuka", "Marima", "Kagaari South", "Ganga", "Kibugua", "Tunyai"] },
      { name: "Chuka/Igambang'ombe", towns: ["Chuka Town", "Igambang'ombe", "Mugumori", "Kathangachini"] },
      { name: "Tharaka North", towns: ["Marimanti", "Nkondi", "Mukothima", "Chiakariga", "Ndagani"] },
      { name: "Tharaka South", towns: ["Kathwana", "Magutuni", "Kibuco", "Ishiara", "Gatunga", "Thurwa"] },
    ],
  },
  {
    name: "Embu",
    center: { lat: -0.5300, lng: 37.4500 },
    zoom: 9,
    subCounties: [
      { name: "Manyatta", towns: ["Embu Town", "Kirimari", "Gaturi South", "Ngenda", "Kamiu", "Kianjokoma"] },
      { name: "Runyenjes", towns: ["Runyenjes", "Kyeni", "Kagaari North", "Gachoka", "Mavuria", "Kiambere"] },
      { name: "Mbeere South", towns: ["Siakago", "Ena", "Mwea", "Kiritiri (Embu)", "Makima"] },
      { name: "Mbeere North", towns: ["Kiritiri", "Ishiara", "Kevote", "Kithimu", "Nthawa", "Gachoka"] },
    ],
  },
  {
    name: "Kitui",
    center: { lat: -1.3682, lng: 38.0116 },
    zoom: 9,
    subCounties: [
      { name: "Mwingi North", towns: ["Mwingi Town", "Tseikuru", "Ngomeni (Kitui)", "Kamuwongo", "Mui", "Nguni"] },
      { name: "Mwingi West", towns: ["Kyuso", "Mumoni", "Nguni", "Mbondoni", "Nguumo"] },
      { name: "Mwingi Central", towns: ["Migwani", "Kiomo", "Nuu", "Enziu", "Mui Coal"] },
      { name: "Kitui West", towns: ["Mutomo", "Ikutha", "Kalungu", "Mutha", "Nzau"] },
      { name: "Kitui Rural", towns: ["Matinyani", "Kwa Vonza", "Zombe", "Mbitini", "Kauwi"] },
      { name: "Kitui Central", towns: ["Kitui Town", "Mulango", "Township (Kitui)", "Miambani", "Wikililye"] },
      { name: "Kitui East", towns: ["Chuluni", "Nzambani", "Voo", "Endau", "Mutito"] },
      { name: "Kitui South", towns: ["Mutito", "Kathonzweni", "Ngombo", "Ikanga", "Athi (Kitui)"] },
    ],
  },
  {
    name: "Machakos",
    center: { lat: -1.5177, lng: 37.2634 },
    zoom: 9,
    subCounties: [
      { name: "Masinga", towns: ["Masinga", "Kivaa", "Matuu", "Ekalakala", "Kiambere (Machakos)"] },
      { name: "Yatta", towns: ["Yatta", "Katangi", "Ndalani", "Matuu (Yatta)", "Ikombe", "Nzaui"] },
      { name: "Kangundo", towns: ["Kangundo", "Tala", "Komarock (Machakos)", "Kinyui", "Mbiuni"] },
      { name: "Matungulu", towns: ["Matungulu", "Tala", "Mbiuni", "Kalama", "Mitaboni"] },
      { name: "Kathiani", towns: ["Kathiani", "Mitaboni", "Kalama", "Kiima Kimwe", "Kithimani"] },
      { name: "Mavoko", towns: ["Athi River", "Mlolongo", "Syokimau", "Mavoko", "Katani", "Bondeni"] },
      { name: "Machakos Town", towns: ["Machakos CBD", "Muvuti", "Mutituni", "Mumbuni", "Kalawa", "Mua Hills"] },
      { name: "Mwala", towns: ["Mwala", "Mbuni", "Makutano (Machakos)", "Kinyui", "Kithembe"] },
    ],
  },
  {
    name: "Makueni",
    center: { lat: -2.2588, lng: 37.8942 },
    zoom: 9,
    subCounties: [
      { name: "Mbooni", towns: ["Mbooni", "Tulimani", "Kiima Kimwe", "Kambu", "Kee", "Iviani"] },
      { name: "Kilome", towns: ["Kilome", "Kasikeu", "Mukaa", "Kalawa (Makueni)", "Ithiani"] },
      { name: "Kaiti", towns: ["Wote", "Kalawa", "Mukaa", "Ilima", "Kola"] },
      { name: "Makueni", towns: ["Wote (Town)", "Nunguni", "Tawa", "Kathonzweni", "Ngai Ndethya"] },
      { name: "Kibwezi West", towns: ["Sultan Hamud", "Emali", "Nguu ya Ndoti", "Nguumo (Makueni)", "Masongaleni"] },
      { name: "Kibwezi East", towns: ["Kibwezi", "Makindu", "Mtito Andei", "Kambu", "Ngai Ndethya"] },
    ],
  },
  {
    name: "Nyandarua",
    center: { lat: -0.1800, lng: 36.3500 },
    zoom: 9,
    subCounties: [
      { name: "Kinangop", towns: ["Njabini", "Engineer", "North Kinangop", "Gathabai", "Magumu", "Nyakio", "Kiburu", "Njambini"] },
      { name: "Kipipiri", towns: ["Shamata", "Kipipiri", "Geta", "Karau", "Wanjohi"] },
      { name: "Ol Kalou", towns: ["Ol Kalou", "Kagaa", "Rurii", "Mirangine", "Kanjuiri", "Githioro"] },
      { name: "Ol Joro Orok", towns: ["Ol Joro Orok", "Wanjohi", "Shamata", "Kirima", "Kiriita"] },
      { name: "Ndaragwa", towns: ["Ndaragwa", "Kiriita", "Kanjuiri", "Leshau", "Karandi"] },
    ],
  },
  {
    name: "Nyeri",
    center: { lat: -0.4167, lng: 36.9500 },
    zoom: 9,
    subCounties: [
      { name: "Tetu", towns: ["Wamagana", "Aguthi", "Iria-ini", "Karima", "Kiganjo (Nyeri)", "Muthengi"] },
      { name: "Kieni", towns: ["Naromoru", "Mweiga", "Chaka", "Mwiyogo", "Ngorano", "Kiganjo", "Burguret", "Naro Moru"] },
      { name: "Mathira", towns: ["Karatina", "Konyu", "Kirimukuyu", "Mahiga", "Mukurwe-ini (Nyeri)", "Tunyai"] },
      { name: "Othaya", towns: ["Othaya", "Mahiga", "Iria-ini", "Miiri", "Chinga", "Ndeiya (Nyeri)"] },
      { name: "Mukurweini", towns: ["Mukurweini", "Giakanja", "Rugi", "Karumande", "Gititu"] },
      { name: "Nyeri Town", towns: ["Nyeri Town", "Ruring'u", "Kamakwa", "Thunuma", "Gatitu", "King'ong'o"] },
    ],
  },
  {
    name: "Kirinyaga",
    center: { lat: -0.6584, lng: 37.3824 },
    zoom: 9,
    subCounties: [
      { name: "Mwea", towns: ["Wanguru", "Mwea Town", "Mutithi", "Thiba", "Tebere", "Ngurubani", "Karaba"] },
      { name: "Gichugu", towns: ["Kerugoya", "Kiamathaga", "Kimunye", "Inoi", "Kianjiru", "Mucagara"] },
      { name: "Ndia", towns: ["Kutus", "Kagio", "Kiine", "Baricho", "Kangaita", "Kianjuki"] },
      { name: "Kirinyaga Central", towns: ["Sagana", "Baricho", "Kianyaga", "Kagumo", "Kerugoya Town", "Kiamutugu"] },
    ],
  },
  {
    name: "Murang'a",
    center: { lat: -0.7833, lng: 37.1500 },
    zoom: 9,
    subCounties: [
      { name: "Kangema", towns: ["Kangema", "Kiria-ini (Kangema)", "Rwathia", "Githanga", "Kigumo (Kangema)", "Kigutha"] },
      { name: "Mathioya", towns: ["Mathioya", "Gitugi", "Kamacharia", "Kiria-ini", "Kihoya", "Karoki", "Ithanga (Mathioya)", "Kagunduini"] },
      { name: "Kiharu", towns: ["Murang'a Town", "Murarandia", "Wangu", "Kenol (Kiharu)", "Kiharu", "Kambirwa", "Kariara"] },
      { name: "Kigumo", towns: ["Kigumo", "Kangari", "Gacharage", "Kihumbu-ini", "Kinyona", "Kiriti"] },
      { name: "Maragwa", towns: ["Maragua", "Makuyu", "Kenol", "Saba Saba (Maragwa)", "Kigumo (Maragwa)", "Mbiri", "Mucharage"] },
      { name: "Kandara", towns: ["Kandara", "Gaichanjiru", "Ithiru", "Ng'enda", "Kimorori", "Murichu"] },
      { name: "Gatanga", towns: ["Gatanga", "Kihumbu", "Ithanga", "Makomboki", "Kahuho", "Muthithi", "Kambiti"] },
      { name: "Murang'a South", towns: ["Saba Saba", "Mbiri", "Kirwara", "Kenyatta (Murang'a)", "Kigumo Town"] },
    ],
  },
  {
    name: "Kiambu",
    center: { lat: -1.0322, lng: 36.8315 },
    zoom: 10,
    subCounties: [
      { name: "Gatundu South", towns: ["Gatundu", "Kiganjo", "Ndarugu", "Kiganjo Market", "Karuri (Gatundu)", "Mang'u", "Kimungu"] },
      { name: "Gatundu North", towns: ["Githiga", "Gakoe", "Kiganjo North", "Karuri wa Gatundu", "Kiamwangi"] },
      { name: "Juja", towns: ["Juja", "Juja Farm", "Kenyatta Road", "Witeithie", "Theta", "Clay Works", "Murera", "Gachororo", "Kalimoni", "Mang'u"] },
      { name: "Thika Town", towns: ["Thika CBD", "Makongeni", "Kamenu", "Ngoigwa", "Gatuanyaga", "Township (Thika)", "Kiandutu", "Biashara"] },
      { name: "Ruiru", towns: ["Ruiru", "Membley", "Mwihoko", "Githua", "Mugutha", "Bypass", "Kahawa Sukari", "Kamiti"] },
      { name: "Githunguri", towns: ["Githunguri", "Kihara", "Ngewa", "Kimunyu", "Ikinu", "Kagwe", "Githiga (Githunguri)"] },
      { name: "Kiambu", towns: ["Kiambu Town", "Kiambu Riabai", "Ndumberi", "Karai", "Tinganga"] },
      { name: "Kiambaa", towns: ["Karuri", "Banana", "Cianda", "Muchatha", "Ndenderu", "Ruaka", "Gitaru"] },
      { name: "Kabete", towns: ["Kabete", "Uthiru", "Muguga", "Gitaru", "Kingeero", "Wangige"] },
      { name: "Kikuyu", towns: ["Kikuyu Town", "Kinoo", "Ondiri", "Kamangu", "Gikambura", "Mutarakwa", "Karai (Kikuyu)"] },
      { name: "Limuru", towns: ["Limuru", "Tigoni", "Lari", "Ndeiya", "Rironi", "Bibirioni", "Gitithia", "Kimende", "Tula"] },
      { name: "Lari", towns: ["Lari", "Kereita", "Kijabe", "Uplands", "Nyamweru", "Naivasha Road", "Kinale"] },
    ],
  },
  {
    name: "Turkana",
    center: { lat: 3.1235, lng: 35.5931 },
    zoom: 8,
    subCounties: [
      { name: "Turkana North", towns: ["Lokichoggio", "Kibish", "Kalobeyei", "Lokwii"] },
      { name: "Turkana West", towns: ["Lodwar", "Kakuma", "Lokichar", "Kalobeyei", "Songot"] },
      { name: "Turkana Central", towns: ["Lodwar Town", "Nauss", "Lorugum", "Nakwamoru"] },
      { name: "Loima", towns: ["Loima", "Nakwamoru", "Lorugum", "Lobei"] },
      { name: "Turkana South", towns: ["Kainuk", "Katilu", "Kalemngorok", "Lokichar"] },
      { name: "Turkana East", towns: ["Lokori", "Kerio Valley", "Lomelo", "Kibish (East)"] },
    ],
  },
  {
    name: "West Pokot",
    center: { lat: 1.6547, lng: 35.1167 },
    zoom: 9,
    subCounties: [
      { name: "West Pokot", towns: ["Kapenguria", "Makutano", "Siyoi", "Kacheliba", "Chepareria", "Suam"] },
      { name: "North Pokot", towns: ["Alale", "Kacheliba", "Kodich", "Kasei", "Kongelai"] },
      { name: "Pokot South", towns: ["Sigor", "Weiwei", "Masol", "Lelan", "Chesegon"] },
      { name: "Kacheliba", towns: ["Kacheliba", "Alale", "Amakuriat", "Orwa"] },
    ],
  },
  {
    name: "Samburu",
    center: { lat: 1.2107, lng: 36.9543 },
    zoom: 9,
    subCounties: [
      { name: "Samburu West", towns: ["Maralal", "Loosuk", "Poro", "Kisima", "Kirisia", "Suguta Marmar"] },
      { name: "Samburu North", towns: ["Baragoi", "South Horr", "Tuum", "Nachola"] },
      { name: "Samburu East", towns: ["Wamba", "Archer's Post", "Kisima", "Ngaremara"] },
    ],
  },
  {
    name: "Trans Nzoia",
    center: { lat: 1.0166, lng: 35.0000 },
    zoom: 10,
    subCounties: [
      { name: "Cherangany", towns: ["Cherangany", "Kaplamai", "Motosiet", "Sitatunga", "Kipsoen"] },
      { name: "Kwanza", towns: ["Kwanza", "Bidii", "Sikhendu", "Makutano (Trans Nzoia)"] },
      { name: "Endebess", towns: ["Endebess", "Matumbei", "Sinyerere", "Kapkoi"] },
      { name: "Saboti", towns: ["Saboti", "Kipsaina", "Matisi", "Tuwan", "Kiminini"] },
      { name: "Kiminini", towns: ["Kiminini", "Kitale CBD", "Waitaluk", "Hospital (Kitale)", "Bidii (Kitale)"] },
    ],
  },
  {
    name: "Uasin Gishu",
    center: { lat: 0.5143, lng: 35.2698 },
    zoom: 10,
    subCounties: [
      { name: "Soy", towns: ["Moi's Bridge", "Ziwa", "Soy", "Burnt Forest", "Turbo East", "Mwanzo"] },
      { name: "Turbo", towns: ["Turbo", "Ngenyilel", "Huruma (Eldoret)", "Tarakwa"] },
      { name: "Moiben", towns: ["Moiben", "Ainabkoi", "Kapsoya", "Chepkumia"] },
      { name: "Ainabkoi", towns: ["Kapsoya", "Ainabkoi", "Kimumu", "Chepkumia", "Kaptagat"] },
      { name: "Kapseret", towns: ["Kapseret", "Langas", "Racecourse", "Pionier", "Megun", "Simat"] },
      { name: "Kesses", towns: ["Kesses", "Eldoret CBD", "Huruma", "Eldoret East", "Eldoret West", "Pioneer", "Elgon View"] },
    ],
  },
  {
    name: "Elgeyo-Marakwet",
    center: { lat: 0.8000, lng: 35.5000 },
    zoom: 9,
    subCounties: [
      { name: "Marakwet East", towns: ["Chesoi", "Kapsowar", "Arror", "Embobut", "Cherangany (Marakwet)", "Soy (Marakwet)"] },
      { name: "Marakwet West", towns: ["Tot", "Lelan", "Siyoi", "Chesongoch", "Kapkenda"] },
      { name: "Keiyo North", towns: ["Iten", "Emsea", "Tambach", "Kaptagat (Keiyo)", "Kamariny"] },
      { name: "Keiyo South", towns: ["Chepkorio", "Kamariny", "Kipsigon", "Chebarus", "Chesoi (South)"] },
    ],
  },
  {
    name: "Nandi",
    center: { lat: 0.1833, lng: 35.1167 },
    zoom: 9,
    subCounties: [
      { name: "Tinderet", towns: ["Tinderet", "Songhor", "Fort Ternan", "Kedowa", "Kunyak"] },
      { name: "Aldai", towns: ["Nandi Hills", "Ndalat", "Kobujoi", "Nandi Hills Town", "Kapsabet East"] },
      { name: "Nandi Hills", towns: ["Nandi Hills Town", "Chepterit", "Maraba (Nandi)", "Chepterwai"] },
      { name: "Chesumei", towns: ["Kapsabet", "Kabiyet", "Lessos", "Kapngetuny", "Chepkunyuk"] },
      { name: "Emgwen", towns: ["Kapsabet Town", "Mosoriot", "Kapkangani", "Kabwareng"] },
      { name: "Mosop", towns: ["Kabiyet", "Ndalat", "Tarakwa", "Chemundu", "Kapkangani"] },
    ],
  },
  {
    name: "Baringo",
    center: { lat: 0.4700, lng: 35.9800 },
    zoom: 9,
    subCounties: [
      { name: "Baringo Central", towns: ["Kabarnet", "Tenges", "Sacho", "Bartabwa", "Eldama Ravine East"] },
      { name: "Baringo North", towns: ["Nginyang", "Ribkwo", "Chemolingot", "Tangulbei", "Kolowa"] },
      { name: "Baringo South", towns: ["Mogotio", "Emining", "Kisanana", "Eldama Ravine", "Kokwa"] },
      { name: "Rokwi", towns: ["Marigat", "Kampi ya Samaki", "Loruk", "Salabani", "Bogoria"] },
      { name: "Tiaty", towns: ["Nginyang", "Tangulbei", "Kolowa", "Silale", "Chemolingot"] },
    ],
  },
  {
    name: "Laikipia",
    center: { lat: 0.2000, lng: 36.7000 },
    zoom: 9,
    subCounties: [
      { name: "Laikipia West", towns: ["Nyahururu", "Rumuruti", "Ndiriti", "Marmanet", "Kinamba", "Shamata (Laikipia)"] },
      { name: "Laikipia East", towns: ["Nanyuki", "Dol Dol", "Kinamba", "Timau (Laikipia)", "Kionyo"] },
      { name: "Laikipia North", towns: ["Ol Moran", "Sipili", "Olmoran", "Mutara", "Ngarua"] },
    ],
  },
  {
    name: "Nakuru",
    center: { lat: -0.3031, lng: 36.0800 },
    zoom: 10,
    subCounties: [
      { name: "Nakuru Town East", towns: ["Nakuru CBD", "Milimani (Nakuru)", "Kivuli", "Section 58", "Biashara", "Pipeline (Nakuru)", "Freetown"] },
      { name: "Nakuru Town West", towns: ["Shabab", "Kaptembwa", "Barut", "Afraha", "Kivuli", "Pangani (Nakuru)", "Mwariki"] },
      { name: "Naivasha", towns: ["Naivasha Town", "Hell's Gate", "Kongoni", "Olkaria", "Gilgil Road", "Karai (Naivasha)", "Mai Mahiu"] },
      { name: "Gilgil", towns: ["Gilgil", "Elementaita", "Mbaruk", "Malewa", "Ndundori"] },
      { name: "Kuresoi South", towns: ["Olenguruone", "Kamwaura", "Sirikwa", "Tinet", "Mauche"] },
      { name: "Kuresoi North", towns: ["Kuresoi", "Keringet", "Amalo", "Olenguruone North", "Marioshoni"] },
      { name: "Subukia", towns: ["Subukia", "Kabazi", "Waseges", "Baraka (Nakuru)"] },
      { name: "Rongai", towns: ["Rongai", "Menengai West", "Mosop", "Soin (Nakuru)"] },
      { name: "Bahati", towns: ["Bahati", "Lanet", "Nakuru North", "Bondeni (Nakuru)", "Githioro (Nakuru)"] },
      { name: "Molo", towns: ["Molo", "Njoro", "Elburgon", "Mau Summit", "Bomet (Nakuru)"] },
    ],
  },
  {
    name: "Narok",
    center: { lat: -1.0834, lng: 35.8718 },
    zoom: 9,
    subCounties: [
      { name: "Kilgoris", towns: ["Kilgoris", "Lolgorian", "Angata", "Ntimama", "Migori Road"] },
      { name: "Emurua Dikirr", towns: ["Emurua Dikirr", "Ilkisonko", "Majimoto"] },
      { name: "Narok North", towns: ["Narok Town", "Olpusimoru", "Nkareta", "Maasai Mara Area", "Nkoilanget"] },
      { name: "Narok East", towns: ["Mau Narok", "Ololunga", "Ndovu", "Nairiti", "Aitong"] },
      { name: "Narok South", towns: ["Sekenani", "Lemek", "Aitong", "Talek", "Mara North"] },
      { name: "Narok West", towns: ["Suswa", "Olkeri", "Enkorika", "Nairiti", "Narok West Market"] },
    ],
  },
  {
    name: "Kajiado",
    center: { lat: -1.8516, lng: 36.7820 },
    zoom: 9,
    subCounties: [
      { name: "Kajiado North", towns: ["Ngong", "Kiserian", "Ongata Rongai", "Ewuaso", "Magadi Road", "Matasia", "Oloolua"] },
      { name: "Kajiado Central", towns: ["Kajiado Town", "Dalalekutuk", "Olkejuado", "Imaroro", "Bissil"] },
      { name: "Kajiado East", towns: ["Kitengela", "Isinya", "Imaroro", "Kaputiei North", "Duka Moja"] },
      { name: "Kajiado West", towns: ["Magadi", "Ewaso Kedong", "Mosiro", "Oloitiptip"] },
      { name: "Kajiado South", towns: ["Loitoktok", "Kimana", "Ilbissil", "Namanga", "Rombo", "Taveta Road"] },
    ],
  },
  {
    name: "Kericho",
    center: { lat: -0.3676, lng: 35.2863 },
    zoom: 10,
    subCounties: [
      { name: "Kipkelion East", towns: ["Londiani", "Sorget", "Kedowa", "Fort Ternan (Kericho)", "Chepkelat"] },
      { name: "Kipkelion West", towns: ["Kipkelion", "Chepng'eno", "Cheptororiet"] },
      { name: "Ainamoi", towns: ["Kericho Town", "Kipchimchim", "Ainamoi", "Hospital (Kericho)", "Kapkugerwet"] },
      { name: "Bureti", towns: ["Litein", "Roret", "Cheboin", "Kapkatet (Bureti)"] },
      { name: "Belgut", towns: ["Kapkatet", "Waldai", "Kabianga", "Cheptarit", "Soin Sigowet"] },
      { name: "Sigowet/Soin", towns: ["Sigowet", "Fort Ternan (Kericho)", "Chemosit"] },
    ],
  },
  {
    name: "Bomet",
    center: { lat: -0.7878, lng: 35.3419 },
    zoom: 9,
    subCounties: [
      { name: "Sotik", towns: ["Sotik", "Merigi", "Ndanai", "Chebangang", "Ndanai Market"] },
      { name: "Chepalungu", towns: ["Longisa", "Sigor (Bomet)", "Chebelion", "Chebunyo", "Chemaner"] },
      { name: "Bomet East", towns: ["Bomet Town", "Chesoen", "Singorwet", "Kapkwen", "Mutarakwa (Bomet)"] },
      { name: "Bomet Central", towns: ["Bomet CBD", "Silibwet", "Tenwek", "Kembu", "Siongiroi"] },
      { name: "Konoin", towns: ["Mulot", "Kaplong", "Bometchi", "Chepalungu (Konoin)", "Ndanai"] },
    ],
  },
  {
    name: "Kakamega",
    center: { lat: 0.2827, lng: 34.7519 },
    zoom: 10,
    subCounties: [
      { name: "Lugari", towns: ["Lugari", "Lumakanda", "Mautuma", "Moi's Bridge (Lugari)", "Turbo (Lugari)"] },
      { name: "Likuyani", towns: ["Likuyani", "Sango", "Kongoni (Kakamega)", "Soy (Kakamega)", "Chemuche"] },
      { name: "Malava", towns: ["Malava", "Chemuche", "Shirere", "Iguhu", "Lureko"] },
      { name: "Lurambi", towns: ["Kakamega CBD", "Amalemba", "Mumboha", "Sheywe", "Nabitsi", "Bukhungu"] },
      { name: "Navakholo", towns: ["Navakholo", "Shirali", "Butsotso", "Eshitambhi", "Shieywe"] },
      { name: "Mumias West", towns: ["Mumias", "Mumias Sugar Belt", "Shianda", "Mwalo", "Butali"] },
      { name: "Mumias East", towns: ["Ekero", "Etenje", "Musanda", "Salaba", "Emaseno"] },
      { name: "Matungu", towns: ["Matungu", "Koyonzo", "Lusheya", "Khalaba", "Mayoni"] },
      { name: "Butere", towns: ["Butere", "South Wanga", "Marama", "Bushiangala", "Mwibona"] },
      { name: "Khwisero", towns: ["Khwisero", "Kisa West", "Ebusiratsi", "Kisa North", "Khayega"] },
      { name: "Shinyalu", towns: ["Shinyalu", "Butsotso East", "Idakho East", "Isukha North", "Ikolomani"] },
      { name: "Ikolomani", towns: ["Ikolomani", "Idakho North", "Idakho West", "Shirali", "Murhanda"] },
    ],
  },
  {
    name: "Vihiga",
    center: { lat: 0.0750, lng: 34.7234 },
    zoom: 10,
    subCounties: [
      { name: "Vihiga", towns: ["Vihiga Town", "Mungoma", "Luanda South", "Kaimosi", "Chavakali (Vihiga)", "Majengo (Vihiga)"] },
      { name: "Sabatia", towns: ["Chavakali", "Ndivisi", "Wodanga", "Vihiga Market", "Mbale"] },
      { name: "Hamisi", towns: ["Hamisi", "Mudete", "Tambua", "Ebuchichifu", "Jepkoyai"] },
      { name: "Luanda", towns: ["Luanda", "Emabungo", "Jepkoyai", "Bunyore North", "Eregi"] },
      { name: "Emuhaya", towns: ["Emuhaya", "Ebubayi", "West Bunyore", "Ebusiloli", "Elukongo"] },
    ],
  },
  {
    name: "Bungoma",
    center: { lat: 0.5635, lng: 34.5606 },
    zoom: 10,
    subCounties: [
      { name: "Mt. Elgon", towns: ["Kapsokwony", "Cheptais", "Kimilili East", "Kopsiro", "Chema"] },
      { name: "Sirisia", towns: ["Sirisia", "Namwela", "Malakisi", "Naitiri (Sirisia)"] },
      { name: "Kabuchai", towns: ["Kabuchai", "Chwele", "Bumula", "Marakaru", "Milo"] },
      { name: "Bumula", towns: ["Bumula", "Naitiri", "Siboti", "Butula (Bumula)", "Kamukuywa"] },
      { name: "Kanduyi", towns: ["Bungoma CBD", "Musikoma", "Khalaba", "Nzoia", "Milo (Kanduyi)"] },
      { name: "Webuye East", towns: ["Webuye", "Lurambi", "Maraka", "Ndalu", "Malaha"] },
      { name: "Webuye West", towns: ["Webuye West", "Mihuu", "Ndivisi", "Sikhendu (Webuye)"] },
      { name: "Kimilili", towns: ["Kimilili", "Kibingei", "Maeni", "Bokoli", "Khalaba (Kimilili)"] },
      { name: "Tongaren", towns: ["Tongaren", "Naitiri", "Mbakalo", "Bidii (Tongaren)", "Matisi"] },
    ],
  },
  {
    name: "Busia",
    center: { lat: 0.4670, lng: 34.1116 },
    zoom: 10,
    subCounties: [
      { name: "Teso North", towns: ["Malaba", "Amagoro", "Ang'urai", "Amukura", "Kolanya"] },
      { name: "Teso South", towns: ["Busia Town", "Nambale", "Odiado", "Alupe", "Ang'urai South"] },
      { name: "Nambale", towns: ["Nambale", "Namwela (Busia)", "Marachi", "Agenga"] },
      { name: "Matayos", towns: ["Matayos", "Marachi North", "Butula", "Madende", "Elukongo (Busia)"] },
      { name: "Butula", towns: ["Butula", "Port Victoria", "Chakol", "Bumala", "Sio Port"] },
      { name: "Funyula", towns: ["Funyula", "Namboboto", "Bulimbi", "Mundere"] },
      { name: "Bunyala", towns: ["Bunyala", "Port Victoria", "Budalangi", "Sio Port", "Bumala B"] },
    ],
  },
  {
    name: "Siaya",
    center: { lat: 0.0607, lng: 34.2880 },
    zoom: 9,
    subCounties: [
      { name: "Gem", towns: ["Yala", "Ukwala", "Usenge", "Sirembe", "Muhanda", "Sega"] },
      { name: "Ugenya", towns: ["Ugenya", "Sigomre", "West Ugenya", "Uranga", "Nyamsenda"] },
      { name: "Ugunja", towns: ["Ugunja", "Sidindi", "Midiwo", "Mundere (Siaya)"] },
      { name: "Alego Usonga", towns: ["Siaya Town", "Usonga", "Bar Kowino", "Malanga", "Kopiyo", "Ligala"] },
      { name: "Bondo", towns: ["Bondo", "Usigu", "Central Sakwa", "Madiany", "Got Regea"] },
      { name: "Rarieda", towns: ["Rarieda", "Ndori", "Lwak", "Uyoma", "Nyilima", "Bar Olengo"] },
    ],
  },
  {
    name: "Kisumu",
    center: { lat: -0.1022, lng: 34.7617 },
    zoom: 11,
    subCounties: [
      { name: "Kisumu East", towns: ["Manyatta", "Nyalenda B", "Kolwa East", "Kajulu", "Kopere"] },
      { name: "Kisumu West", towns: ["Kisumu CBD", "Milimani (Kisumu)", "Kondele", "Nyalenda A", "Obunga", "Mamboleo"] },
      { name: "Kisumu Central", towns: ["Kisumu North", "Market Milimani", "Railways", "Shauri Moyo (Kisumu)", "Kibuye"] },
      { name: "Seme", towns: ["Central Seme", "East Seme", "West Seme", "Usonga", "Lwak"] },
      { name: "Nyando", towns: ["Ahero", "Awasi", "Kobura", "Miwani (Nyando)", "Kabonyo"] },
      { name: "Muhoroni", towns: ["Muhoroni", "Chemelil", "Miwani", "Koru", "Songhor (Muhoroni)"] },
      { name: "Nyakach", towns: ["Nyakach", "South East Nyakach", "West Nyakach", "Pap Onditi", "Kombewa"] },
    ],
  },
  {
    name: "Homa Bay",
    center: { lat: -0.5273, lng: 34.4571 },
    zoom: 9,
    subCounties: [
      { name: "Kasipul", towns: ["Oyugis", "Rodi Kopany", "West Kasipul", "Olare", "Oriang"] },
      { name: "Kabondo Kasipul", towns: ["Kabondo", "East Kamagambo", "Kendu Bay (Kabondo)"] },
      { name: "Karachuonyo", towns: ["Kendu Bay", "North Karachuonyo", "West Karachuonyo", "Homa Hills", "Pala"] },
      { name: "Rangwe", towns: ["Rangwe", "Central Karachuonyo", "Kagan", "Pala (Rangwe)"] },
      { name: "Homa Bay Town", towns: ["Homa Bay CBD", "Piny Owacho", "Kabuoro", "Kanyaluo"] },
      { name: "Ndhiwa", towns: ["Ndhiwa", "Kanyamwa Kosewe", "Kanyamwa Kotieno", "Mirogi", "Gendia"] },
      { name: "Suba North", towns: ["Mbita", "Mfangano", "Kasgunga", "Rusinga Island", "Gembe"] },
      { name: "Suba South", towns: ["Sindo", "Gembe", "Ruma", "Kaksingri", "Magunga"] },
    ],
  },
  {
    name: "Migori",
    center: { lat: -1.0636, lng: 34.4731 },
    zoom: 9,
    subCounties: [
      { name: "Rongo", towns: ["Rongo", "North Kamagambo", "South Kamagambo", "Kanyamkago", "Wiga"] },
      { name: "Awendo", towns: ["Awendo", "West Kanyamkago", "North Kanyamkago", "Macalder", "Oruba"] },
      { name: "Suna East", towns: ["Migori Town", "Suna", "Kakrao", "Uriri (Suna)", "God Jope"] },
      { name: "Suna West", towns: ["Wasimbete", "Kwa", "God Jope", "Rodi", "Kaler"] },
      { name: "Uriri", towns: ["Uriri", "Central Kanyamkago", "East Kanyamkago", "Rapogi", "Sori (Uriri)"] },
      { name: "Nyatike", towns: ["Nyatike", "Sori", "Muhuru Bay", "Macalder (Nyatike)", "Got Kachola"] },
      { name: "Kuria West", towns: ["Kehancha", "Ntimaru West", "Isibania", "Kegonga", "Masaba (Kuria)"] },
      { name: "Kuria East", towns: ["Kuria East", "Ntimaru East", "Mabera", "Tarime (Border)", "Tagare"] },
    ],
  },
  {
    name: "Kisii",
    center: { lat: -0.6817, lng: 34.7666 },
    zoom: 10,
    subCounties: [
      { name: "Bonchari", towns: ["Suneka", "Bonchari", "South Mugirango", "Rongo (Kisii)", "Masige"] },
      { name: "South Mugirango", towns: ["Ogembo", "West Mugirango", "Borabu", "Keumbu", "Ichuni"] },
      { name: "Bomachoge Borabu", towns: ["Keroka", "Masimba", "Borabu", "Rigoma (Kisii)", "Nyansiongo (Kisii)"] },
      { name: "Bobasi", towns: ["Manga", "Sameta", "Bobasi Central", "Sengera", "Ichuni (Bobasi)"] },
      { name: "Bomachoge Chache", towns: ["Kisii Town South", "Bogetenga", "Kenyenya", "Gesusu"] },
      { name: "Nyaribari Masaba", towns: ["Nyaribari Masaba", "Ibeno", "Rianyakoe", "Bobaracho"] },
      { name: "Nyaribari Chache", towns: ["Kisii CBD", "Nyanchwa", "Mwembe", "Daraja Mbili", "Hospital (Kisii)"] },
      { name: "Kitutu Chache North", towns: ["Kitutu Chache", "Daraja Mbili", "Keumbu", "Etago"] },
      { name: "Kitutu Chache South", towns: ["Kisii Town", "Nyokado", "Riosiri", "Kiamokama"] },
    ],
  },
  {
    name: "Nyamira",
    center: { lat: -0.5670, lng: 34.9350 },
    zoom: 10,
    subCounties: [
      { name: "Kitutu Masaba", towns: ["Nyamira Town", "Gesima", "Nyansiongo", "Kemera", "Tombe"] },
      { name: "West Mugirango", towns: ["Rigoma", "Gesieka", "Magwagwa", "Bokeira", "Nkobe"] },
      { name: "North Mugirango", towns: ["Manga (Nyamira)", "Ekerenyo", "Metembe", "Bosamaro", "Botundu"] },
      { name: "Borabu", towns: ["Borabu", "Masaba", "Matongo", "Nyaramba", "Ikoba"] },
    ],
  },
];

// Get county data by name
export function getCountyData(countyName) {
  return KENYA_COUNTIES.find(c => c.name === countyName) || null;
}

// Get sub-county names for a county
export function getSubCountyNames(countyName) {
  const county = getCountyData(countyName);
  return county ? county.subCounties.map(sc => sc.name) : [];
}

// Get towns for a specific sub-county
export function getTownsForSubCounty(countyName, subCountyName) {
  const county = getCountyData(countyName);
  if (!county) return [];
  const sc = county.subCounties.find(s => s.name === subCountyName);
  return sc ? sc.towns : [];
}

// Get all towns in a county (flat list, for when no sub-county selected)
export function getAllTownsForCounty(countyName) {
  const county = getCountyData(countyName);
  if (!county) return [];
  return county.subCounties.flatMap(sc => sc.towns);
}